use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct Mif {
    pub width: usize,
    pub depth: usize,
    pub width_b: Option<usize>,
    pub depth_b: Option<usize>,
    pub data: Vec<String>,
}

pub fn sanitize_module_name(name: &str) -> String {
    let mut out = String::new();
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() || out.as_bytes()[0].is_ascii_digit() {
        out.insert(0, '_');
    }
    out
}

pub fn addr_width(depth: usize) -> usize {
    let mut width = 0usize;
    let mut value = depth.saturating_sub(1);
    while value > 0 {
        width += 1;
        value >>= 1;
    }
    width.max(1)
}

pub fn parse_mif(path: &Path) -> Result<Mif, String> {
    let text = fs::read_to_string(path)
        .map_err(|err| format!("failed to read MIF {}: {err}", path.display()))?;
    let mut width = None;
    let mut depth = None;
    let mut width_b = None;
    let mut depth_b = None;
    let mut address_radix = Radix::Hex;
    let mut data_radix = Radix::Hex;
    let mut raw_entries: Vec<(usize, String)> = Vec::new();

    for line in text.lines() {
        let line = strip_mif_comments(line).trim().to_string();
        if line.is_empty() {
            continue;
        }

        let upper = line.to_ascii_uppercase();
        if let Some(value) = assignment_value(&upper, "WIDTH") {
            width = Some(parse_decimal(value)?);
            continue;
        }
        if let Some(value) = assignment_value(&upper, "DEPTH") {
            depth = Some(parse_decimal(value)?);
            continue;
        }
        if let Some(value) = assignment_value(&upper, "WIDTHA") {
            width = Some(parse_decimal(value)?);
            continue;
        }
        if let Some(value) = assignment_value(&upper, "DEPTHA") {
            depth = Some(parse_decimal(value)?);
            continue;
        }
        if let Some(value) = assignment_value(&upper, "WIDTHB") {
            width_b = Some(parse_decimal(value)?);
            continue;
        }
        if let Some(value) = assignment_value(&upper, "DEPTHB") {
            depth_b = Some(parse_decimal(value)?);
            continue;
        }
        if let Some(value) = assignment_value(&upper, "ADDRESS_RADIX") {
            address_radix = Radix::parse(value)?;
            continue;
        }
        if let Some(value) = assignment_value(&upper, "DATA_RADIX") {
            data_radix = Radix::parse(value)?;
            continue;
        }

        if let Some((address, value)) = line.split_once(':') {
            let value = value.trim().trim_end_matches(';').trim();
            let addresses = parse_addresses(address.trim(), address_radix)?;
            let normalized = normalize_value(value, data_radix)?;
            for address in addresses {
                raw_entries.push((address, normalized.clone()));
            }
        }
    }

    let width = width.ok_or_else(|| "MIF missing WIDTH or WIDTHA".to_string())?;
    let depth = depth.ok_or_else(|| "MIF missing DEPTH or DEPTHA".to_string())?;
    if width == 0 || depth == 0 {
        return Err("MIF WIDTH and DEPTH must be non-zero".to_string());
    }

    let digits = width.div_ceil(4);
    let mut data = vec!["0".repeat(digits); depth];
    for (address, value) in raw_entries {
        if address < depth {
            data[address] = pad_hex_to_width(&value, digits);
        }
    }

    Ok(Mif {
        width,
        depth,
        width_b,
        depth_b,
        data,
    })
}

pub fn generate_pll_verilog(module_name: &str, divide: usize, gates: usize) -> String {
    let module_name = sanitize_module_name(module_name);
    let divide_literal = format!("{divide}.0");
    if gates == 50 {
        format!(
            r#"// Generated by UFDE+ IP generator.
// FPGA gates: 50W, primitive: DCM, divide: {divide}

module {module_name} (
    input wire clk_in,
    input wire clk_fb,
    input wire rst,
    output wire clk_dv,
    output wire clk0,
    output wire clk90,
    output wire clk180,
    output wire clk270,
    output wire clk2x,
    output wire clk2x180,
    output wire locked
);
    DCM #(
        .CLKDV_DIVIDE({divide_literal})
    ) dcm_inst (
        .CK(clk_in),
        .CLKFB(clk_fb),
        .RST(rst),
        .CLKDV(clk_dv),
        .CLK0(clk0),
        .CLK90(clk90),
        .CLK180(clk180),
        .CLK270(clk270),
        .CLK2X(clk2x),
        .CLK2X180(clk2x180),
        .LOCKED(locked),
        .CTLMODE(1'b0),
        .CTLSEL2(1'b0),
        .CTLSEL1(1'b0),
        .CTLSEL0(1'b0),
        .CTLGO(1'b0),
        .CTLOSC1(1'b0),
        .CTLOSC2(1'b0),
        .PSINCDEC(1'b0),
        .PSEN(1'b0),
        .PSCLK(1'b0),
        .STSADRS3(1'b0),
        .STSADRS2(1'b0),
        .STSADRS1(1'b0),
        .STSADRS0(1'b0),
        .FREEZEDFS(1'b0),
        .FREEZEDLL(1'b0),
        .DSSEN(1'b0)
    );
endmodule
"#
        )
    } else {
        format!(
            r#"// Generated by UFDE+ IP generator.
// FPGA gates: 30W, primitive: DLL, divide: {divide}

module {module_name} (
    input wire clk_in,
    input wire clk_fb,
    input wire rst,
    output wire clk_dv,
    output wire clk0,
    output wire clk90,
    output wire clk180,
    output wire clk270,
    output wire clk2x,
    output wire clk2x90,
    output wire locked
);
    DLL #(
        .CLKDV_DIVIDE({divide_literal})
    ) dll_inst (
        .CK(clk_in),
        .CLKFB(clk_fb),
        .RST(rst),
        .CLKDV(clk_dv),
        .CLK0(clk0),
        .CLK90(clk90),
        .CLK180(clk180),
        .CLK270(clk270),
        .CLK2X(clk2x),
        .CLK2X90(clk2x90),
        .LOCKED(locked)
    );
endmodule
"#
        )
    }
}

pub fn generate_bram_verilog(mif_path: &Path, mif: &Mif) -> String {
    let stem = mif_path
        .file_stem()
        .and_then(|value| value.to_str())
        .unwrap_or("ufde_bram");
    let module_name = sanitize_module_name(stem);
    let addr_width_a = addr_width(mif.depth);
    let width_b = mif.width_b.unwrap_or(mif.width);
    let depth_b = mif.depth_b.unwrap_or(mif.depth);
    let addr_width_b = addr_width(depth_b);
    let total_bits = mif.width.saturating_mul(mif.depth);

    let mut init_lines = String::new();
    for (address, value) in mif.data.iter().enumerate() {
        if value.chars().any(|ch| ch != '0') {
            init_lines.push_str(&format!(
                "        mem_bits[{} +: {}] = {}'h{};\n",
                address * mif.width,
                mif.width,
                mif.width,
                value
            ));
        }
    }
    if init_lines.is_empty() {
        init_lines.push_str("        mem_bits = 0;\n");
    } else {
        init_lines.insert_str(0, "        mem_bits = 0;\n");
    }

    if mif.width_b.is_some() || mif.depth_b.is_some() {
        format!(
            r#"// Generated by UFDE+ IP generator from {mif_path}.

module {module_name} (
    input wire clka,
    input wire rsta,
    input wire ena,
    input wire wea,
    input wire [{addr_width_a_minus}:0] addra,
    input wire [{width_a_minus}:0] dina,
    output reg [{width_a_minus}:0] douta,
    input wire clkb,
    input wire rstb,
    input wire enb,
    input wire web,
    input wire [{addr_width_b_minus}:0] addrb,
    input wire [{width_b_minus}:0] dinb,
    output reg [{width_b_minus}:0] doutb
);
    localparam integer TOTAL_BITS = {total_bits};
    reg [TOTAL_BITS-1:0] mem_bits;

    initial begin
{init_lines}    end

    always @(posedge clka) begin
        if (rsta) begin
            douta <= {width_a}'b0;
        end else if (ena) begin
            if (wea) begin
                mem_bits[addra * {width_a} +: {width_a}] <= dina;
                douta <= dina;
            end else begin
                douta <= mem_bits[addra * {width_a} +: {width_a}];
            end
        end
    end

    always @(posedge clkb) begin
        if (rstb) begin
            doutb <= {width_b}'b0;
        end else if (enb) begin
            if (web) begin
                mem_bits[addrb * {width_b} +: {width_b}] <= dinb;
                doutb <= dinb;
            end else begin
                doutb <= mem_bits[addrb * {width_b} +: {width_b}];
            end
        end
    end
endmodule
"#,
            mif_path = mif_path.display(),
            addr_width_a_minus = addr_width_a - 1,
            width_a_minus = mif.width - 1,
            addr_width_b_minus = addr_width_b - 1,
            width_b_minus = width_b - 1,
            width_a = mif.width,
        )
    } else {
        format!(
            r#"// Generated by UFDE+ IP generator from {mif_path}.

module {module_name} (
    input wire clk,
    input wire rst,
    input wire en,
    input wire we,
    input wire [{addr_width_a_minus}:0] addr,
    input wire [{width_a_minus}:0] din,
    output reg [{width_a_minus}:0] dout
);
    localparam integer TOTAL_BITS = {total_bits};
    reg [TOTAL_BITS-1:0] mem_bits;

    initial begin
{init_lines}    end

    always @(posedge clk) begin
        if (rst) begin
            dout <= {width_a}'b0;
        end else if (en) begin
            if (we) begin
                mem_bits[addr * {width_a} +: {width_a}] <= din;
                dout <= din;
            end else begin
                dout <= mem_bits[addr * {width_a} +: {width_a}];
            end
        end
    end
endmodule
"#,
            mif_path = mif_path.display(),
            addr_width_a_minus = addr_width_a - 1,
            width_a_minus = mif.width - 1,
            width_a = mif.width,
        )
    }
}

pub fn write_file(path: &Path, content: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|err| format!("failed to create {}: {err}", parent.display()))?;
    }
    fs::write(path, content).map_err(|err| format!("failed to write {}: {err}", path.display()))
}

pub fn output_path_for_mif(mif_path: &Path) -> PathBuf {
    let mut out = mif_path.to_path_buf();
    out.set_extension("v");
    out
}

fn strip_mif_comments(line: &str) -> String {
    let mut out = line.to_string();
    if let Some((prefix, _)) = out.split_once("--") {
        out = prefix.to_string();
    }
    if let Some(start) = out.find('%') {
        if let Some(end) = out[start + 1..].find('%') {
            out.replace_range(start..=start + end + 1, "");
        }
    }
    out
}

fn assignment_value<'a>(line: &'a str, key: &str) -> Option<&'a str> {
    line.strip_prefix(key)?
        .trim_start()
        .strip_prefix('=')?
        .trim()
        .trim_end_matches(';')
        .trim()
        .into()
}

fn parse_decimal(value: &str) -> Result<usize, String> {
    value
        .parse::<usize>()
        .map_err(|err| format!("invalid decimal value {value}: {err}"))
}

#[derive(Debug, Clone, Copy)]
enum Radix {
    Bin,
    Dec,
    Hex,
}

impl Radix {
    fn parse(value: &str) -> Result<Self, String> {
        match value.trim().trim_end_matches(';').to_ascii_uppercase().as_str() {
            "BIN" | "BINARY" => Ok(Self::Bin),
            "DEC" | "UNS" | "DECIMAL" => Ok(Self::Dec),
            "HEX" | "HEXADECIMAL" => Ok(Self::Hex),
            other => Err(format!("unsupported MIF radix {other}")),
        }
    }
}

fn parse_addresses(value: &str, radix: Radix) -> Result<Vec<usize>, String> {
    let value = value.trim();
    if value.starts_with('[') && value.ends_with(']') {
        let range = &value[1..value.len() - 1];
        let (start, end) = range
            .split_once("..")
            .ok_or_else(|| format!("invalid MIF address range {value}"))?;
        let start = parse_usize_radix(start.trim(), radix)?;
        let end = parse_usize_radix(end.trim(), radix)?;
        if start > end {
            return Err(format!("invalid descending MIF address range {value}"));
        }
        Ok((start..=end).collect())
    } else {
        Ok(vec![parse_usize_radix(value, radix)?])
    }
}

fn parse_usize_radix(value: &str, radix: Radix) -> Result<usize, String> {
    let value = value.trim();
    match radix {
        Radix::Bin => usize::from_str_radix(value, 2),
        Radix::Dec => value.parse::<usize>(),
        Radix::Hex => usize::from_str_radix(value, 16),
    }
    .map_err(|err| format!("invalid MIF address {value}: {err}"))
}

fn normalize_value(value: &str, radix: Radix) -> Result<String, String> {
    let value = value.trim().trim_end_matches(';').trim();
    match radix {
        Radix::Hex => Ok(value.trim_start_matches("0x").to_ascii_uppercase()),
        Radix::Bin => {
            let mut bits = value.to_string();
            let rem = bits.len() % 4;
            if rem != 0 {
                bits = format!("{}{}", "0".repeat(4 - rem), bits);
            }
            let mut hex = String::new();
            for chunk in bits.as_bytes().chunks(4) {
                let chunk = std::str::from_utf8(chunk).map_err(|err| err.to_string())?;
                let nibble =
                    u8::from_str_radix(chunk, 2).map_err(|err| format!("invalid BIN value: {err}"))?;
                hex.push_str(&format!("{nibble:X}"));
            }
            Ok(hex)
        }
        Radix::Dec => {
            let value = value
                .parse::<u128>()
                .map_err(|err| format!("invalid DEC value {value}: {err}"))?;
            Ok(format!("{value:X}"))
        }
    }
}

fn pad_hex_to_width(value: &str, digits: usize) -> String {
    let value = value.trim_start_matches('0');
    let value = if value.is_empty() { "0" } else { value };
    if value.len() >= digits {
        value[value.len() - digits..].to_ascii_uppercase()
    } else {
        format!("{}{}", "0".repeat(digits - value.len()), value.to_ascii_uppercase())
    }
}
